# Generated by Django 5.1 on 2024-08-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet_transaction_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="label",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
