# Generated by Django 5.1 on 2024-08-15 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallet_transaction_api", "0002_alter_wallet_label"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-amount"]},
        ),
    ]
