# Generated by Django 5.1 on 2024-08-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet_transaction_api", "0003_alter_transaction_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=18, max_digits=36),
        ),
    ]
